### ISSUE TITLE
Welcome to our club link is no longer active.

### ISSUE THREAD

**Issue by Smeagol2069** [rydixulous/Discord-Resources-n-More#34]
Found under fun links, welcome-to-our.club no longer embeds the video and when sent on Discord shows a "This domain may be for sale" error message. I suggest removing it as I do not know who the owner is.

**Comment by Eyeballs360** [comment]
Good morning Smeagol, 
Thanks for bringing this to our attention, we'll remove the link from the list or update it shortly. $
