### ISSUE TITLE
Resource Addition

### ISSUE THREAD

**Issue by vagabondlol** [rydixulous/Discord-Resources-n-More#43]
1. The name of the resource.
A) Polywork
2. A good , objective and straight to the point description to the resource.
Avoid using superlatives. e.g. "best", "beautiful" etc.
A) Polywork is a professional social network where people highlight the things they've been up to - work, life, learnings, plans & more.
3. A link to to the resource.
A) https://polywork.com
4. Credit to the creator (ID)
A) 397142169506414592 (not creator, just suggester since creator isn't known on discord)
5. A placement inside the wiki (sub section or sub sub section if necessary).
A) No clue, this really isn't a discord resource so that's up to you lol

**Comment by rydixulous** [comment]
what the actual fuck, but we got it done.
